name: npm-publish
on:
  push:
    tags:        
      - '**' # Push events to v1 tag
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm install
          npm run build
          npm --no-git-tag-version -f version from-git
          git add .
          git commit -m "update version to: ${{  github.ref_name }}"
          git push origin HEAD:main
          git tag -d ${{  github.ref_name }} && git push origin :refs/tags/${{  github.ref_name }}
          git tag  ${{  github.ref_name }} origin HEAD:main
          git push --tags
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: false
